<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-SAPACB4E" failures="2" tests="3" name="NetBanking(failed)" time="0.062" errors="0" timestamp="2022-11-17T19:44:19 IST">
  <testcase classname="learnSelenium.TestNg3" name="e" time="0.009">
    <failure type="java.lang.AssertionError" message="did not expect [QA] but found [QA]">
      <![CDATA[java.lang.AssertionError: did not expect [QA] but found [QA]
at learnSelenium.TestNg3.e(TestNg3.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- e -->
  <testcase classname="learnSelenium.TestNG5" name="login" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at learnSelenium.TestNG5.login(TestNG5.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="learnSelenium.TestNG5" name="payment" time="0.0">
    <skipped/>
  </testcase> <!-- payment -->
</testsuite> <!-- NetBanking(failed) -->
